name: CI Pipeline
on:
  push:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Image
        run: docker build -t my-app:latest .

      - name: Run Unit Tests (optional)
        run: echo "No tests yet"

      - name: Archive Docker image (optional)
        run: docker save my-app:latest > my-app.tar
